// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxpejdoeexsachjpodsz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4cGVqZG9lZXhzYWNoanBvZHN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MjE4NDIsImV4cCI6MjA2Nzk5Nzg0Mn0.dfjO4DU4e0lf4JZRO3YKYBY-FmfuazZ4tld_WA5tE0E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});